/**
 * Deskripsi singkat (Bahasa Indonesia) tentang isi tiap tabel legacy.
 * DB read-only tanpa TABLE_COMMENT yang berarti, jadi dipetakan manual di sini.
 * Dipakai oleh /api/schema → ditampilkan di halaman Skema Database.
 */
export const TABLE_DESCRIPTIONS: Record<string, string> = {
  _access: "Daftar menu & kode hak akses modul aplikasi.",
  _ads: "Banner/iklan promosi (posisi, sponsor, link, periode tayang).",
  _ads_klik: "Log klik pada banner/iklan per kanal.",
  _api_klien: "Kredensial klien/vendor untuk akses API (access key).",
  _api_log: "Log pemanggilan API (halaman, domain, parameter, IP).",
  _bagian: "Master bagian/unit organisasi.",
  _bagian_divisi: "Master divisi di bawah tiap bagian.",
  _category: "Master kategori konten (hierarkis: parent/level).",
  _chat_friend: "Relasi pertemanan chat antar member.",
  _chat_msg: "Pesan chat personal antar member.",
  _city: "Master kota/kabupaten beserta provinsi.",
  _classroom: "Kelas/batch pelaksanaan training (in-class & e-learning). Sumber modul Enrollment.",
  _classroom2_jadwal: "Jadwal sesi untuk kelas versi 2 (tanggal & jumlah sesi).",
  _classroom2_presensi: "Presensi peserta per sesi kelas versi 2.",
  _classroom_agenda: "Agenda/rundown acara sebuah kelas (narasumber, waktu).",
  _classroom_attendance: "Catatan kehadiran peserta kelas per kanal.",
  _classroom_chat: "Diskusi/komentar dalam modul atau materi kelas.",
  _classroom_evaluasi_lv3_header: "Header evaluasi pelatihan Level 3 (Kirkpatrick) per kelas.",
  _classroom_evaluasi_lv3_pairing: "Pasangan penilai–dinilai pada evaluasi Level 3.",
  _classroom_evaluasi_lv3_rekap: "Rekap nilai pre/post-test evaluasi Level 3 per peserta.",
  _classroom_member: "Pendaftaran peserta pada kelas (enrollment), termasuk progres & nilai. Sumber daftar peserta.",
  _classroom_member_test: "Status pengerjaan tes (pretest/quiz/evaluasi/kompetensi) peserta kelas.",
  _classroom_member_v2: "Pendaftaran peserta kelas versi 2.",
  _classroom_modul_member: "Pengumpulan tugas (assignment) per modul oleh peserta.",
  _classroom_soal: "Bank soal kuis/tes untuk kelas.",
  _classroom_soal_cat: "Kategori bank soal kelas.",
  _come_keahlian: "Master keahlian untuk modul Coaching & Mentoring (CoMe).",
  _come_konfig: "Konfigurasi modul Coaching & Mentoring.",
  _come_member: "Pendaftaran coach/mentor & mentee per tahun.",
  _come_member_profil: "Profil peserta coaching/mentoring (atasan, keahlian, pendidikan).",
  _come_paket_sesi: "Paket sesi coaching/mentoring (pembimbing, peserta, JPL, perencanaan).",
  _come_paket_sesi_detail: "Rincian tiap sesi coaching (tanggal, catatan, evidence).",
  _come_paket_sesi_rating: "Penilaian/skor paket sesi coaching.",
  _come_paket_verifikasi_jpl: "Verifikasi JPL paket sesi coaching.",
  _contact: "Pesan masuk dari form kontak.",
  _content: "Konten pembelajaran/artikel/media (knowledge management).",
  _content_catgroup: "Pengelompokan kategori konten.",
  _content_comment: "Komentar pada konten.",
  _content_download: "Log unduhan konten oleh member.",
  _content_hits: "Log view/akses konten per member & kanal.",
  _content_tags: "Tag/label konten.",
  _content_type: "Master tipe konten.",
  _culture: "Program/modul Culture (budaya perusahaan), strukturnya mirip kelas.",
  _culture_chat: "Diskusi dalam modul Culture.",
  _culture_member: "Pendaftaran peserta modul Culture.",
  _culture_member2: "Pendaftaran peserta modul Culture (versi 2).",
  _culture_member_test: "Status tes peserta modul Culture.",
  _culture_soal: "Bank soal modul Culture.",
  _culture_soal_cat: "Kategori bank soal Culture.",
  _custom_data: "Penyimpanan data generik (label–value) lintas fitur.",
  _expert: "Profil/forum fitur Ask the Expert.",
  _expert_category: "Kategori topik Ask the Expert.",
  _expert_chat: "Percakapan tanya-jawab dengan expert.",
  _expert_comment: "Komentar/rating pada expert.",
  _expert_member: "Daftar expert/narasumber.",
  _expert_setting: "Pengaturan notifikasi expert.",
  _expert_suggest: "Usulan expert dari member.",
  _forum: "Forum diskusi umum.",
  _forum_chat: "Pesan dalam forum diskusi.",
  _forum_group: "Forum diskusi khusus grup/entitas.",
  _forum_group_actions: "Log aksi pada forum grup.",
  _forum_group_chat: "Pesan dalam forum grup.",
  _forum_group_suggest: "Usulan forum grup.",
  _forum_suggest: "Usulan topik forum.",
  _group: "Master entitas/perusahaan (grup), mis. PTPN & anak usaha. Sumber 'entitas' peserta.",
  _helper_invoice: "Rekap pembantu invoice pelatihan per grup (jumlah peserta, presensi).",
  _idp: "Individual Development Plan — rencana pengembangan diri member.",
  _inbox: "Kotak pesan internal/pemberitahuan.",
  _jabatan: "Master jabatan beserta level & grup.",
  _kamus: "Kamus istilah.",
  _klien: "Master klien/tenant aplikasi.",
  _kompetensi: "Definisi modul uji kompetensi.",
  _kompetensi_group: "Penugasan uji kompetensi ke grup.",
  _kompetensi_jabatan: "Penugasan uji kompetensi ke jabatan.",
  _kompetensi_member: "Hasil/level kompetensi per member.",
  _kompetensi_prasyarat: "Prasyarat (kelas) untuk mengikuti uji kompetensi.",
  _kompetensi_soal: "Bank soal uji kompetensi (berlevel).",
  _learning_formal_external: "Pembelajaran formal eksternal yang diakui (JPL).",
  _learning_from_experience: "Pembelajaran dari pengalaman/proyek (JPL).",
  _learning_from_other: "Pembelajaran dari sumber lain/coaching eksternal (JPL).",
  _learning_katalog: "Katalog program training (definisi). Sumber modul Katalog Training.",
  _learning_kategori: "Master kategori/metode pembelajaran (key element).",
  _learning_kategori_jpl: "Target JPL per kategori per tahun.",
  _learning_mp_rekap: "Rekap man-power JPL pembelajaran per member/tahun.",
  _learning_mp_rekap_excel: "Rekap JPL pembelajaran untuk ekspor Excel.",
  _learning_realisasi_anggaran: "Realisasi anggaran pembelajaran per grup/bulan.",
  _learning_target_anggaran: "Target anggaran pembelajaran per grup/tahun.",
  _learning_wallet_akademi: "Master akademi penyelenggara (Learning Wallet).",
  _learning_wallet_classroom: "Katalog kelas eksternal/Learning Wallet (berjadwal, ada penyelenggara).",
  _learning_wallet_konfigurasi: "Konfigurasi Learning Wallet per tahun/kategori.",
  _learning_wallet_konfig_group: "Konfigurasi nominal wallet per grup/member/level.",
  _learning_wallet_nilai: "Nilai pre/post-test pengajuan Learning Wallet.",
  _learning_wallet_pengajuan: "Pengajuan pelatihan via Learning Wallet (harga, status approval).",
  _learning_wallet_penyelenggara: "Master penyelenggara/vendor Learning Wallet.",
  _learning_wallet_sekolah: "Master sekolah/lembaga Learning Wallet.",
  _learning_wallet_serapan: "Serapan anggaran & JPL Learning Wallet per member.",
  _learning_wallet_strategi: "Pilar/strategi pembelajaran (Learning Wallet).",
  _learning_wallet_usulan: "Usulan pelatihan dari member (Learning Wallet).",
  _learning_wallet_wishlist: "Wishlist kelas Learning Wallet per member.",
  _learning_wishlist_konfigurasi: "Konfigurasi fitur wishlist pembelajaran.",
  _learning_wishlist_track_member: "Tracking member pada wishlist pembelajaran.",
  _learning_wishlist_v2: "Wishlist katalog training per member (versi 2).",
  _linkedin_acc: "Data akun LinkedIn karyawan.",
  _media: "Berkas media (gambar/dokumen) terkait konten.",
  _media_download: "Log unduhan media.",
  _member: "Master karyawan/peserta (akun pengguna aplikasi). Sumber data peserta.",
  _member_activity: "Log aktivitas member.",
  _member_bagian_divisi: "Penempatan member pada bagian/divisi per tahun.",
  _member_bidang: "Master bidang.",
  _member_block: "Daftar member yang diblokir.",
  _member_bookmark: "Bookmark konten oleh member.",
  _member_category: "Relasi member–kategori.",
  _member_device_token: "Token perangkat untuk push notification.",
  _member_level: "Master level member.",
  _member_level_karyawan: "Master level/jenjang karyawan (BOD-1 dst). Sumber 'level' peserta.",
  _member_poin: "Riwayat perolehan poin member (gamifikasi).",
  _member_poin_level: "Tingkatan poin & reward.",
  _member_poin_setting: "Pengaturan pemberian poin.",
  _member_poin_setting_monthly: "Pengaturan poin bulanan.",
  _member_reset: "Permintaan reset password member.",
  _member_saldo: "Saldo/insentif member.",
  _member_saldo_setting: "Pengaturan saldo per grup.",
  _member_setting: "Pengaturan & token push notification member.",
  _member_x_user: "Pemetaan member ke akun user (admin).",
  _mfa: "Token multi-factor authentication.",
  _movies: "Konten video.",
  _notifikasi_v2: "Notifikasi dalam aplikasi (versi 2).",
  _notif_log: "Log pengiriman push notification.",
  _nps_jawab: "Jawaban survei NPS/feedback pelatihan.",
  _nps_set_soal: "Set soal NPS per kelas/pengajar.",
  _nps_soal: "Master soal NPS/feedback.",
  _pair_learning_katalog_divisi: "Pemetaan katalog training ke divisi.",
  _pa_v2_activity_log: "Log aktivitas modul Project Assignment v2.",
  _pa_v2_member: "Anggota tim Project Assignment v2.",
  _pa_v2_project: "Proyek pada modul Project Assignment v2.",
  _pa_v2_proposal: "Proposal/lamaran peran pada proyek v2.",
  _pa_v2_report: "Laporan hasil Project Assignment v2.",
  _pelatihan: "Event/agenda pelatihan (banner & QR presensi).",
  _pelatihan_member: "Pendaftaran peserta event pelatihan.",
  _pesan_direksi: "Pesan/sambutan direksi per grup.",
  _project_assignment: "Penugasan proyek (PA) sebagai metode pembelajaran.",
  _project_assignment_detail: "Rincian deliverable/outcome penugasan proyek.",
  _project_assignment_progress_log: "Log progres penugasan proyek.",
  _quotes: "Kutipan/motivasi.",
  _rekap_classroom_excel: "Rekap pelatihan per peserta untuk ekspor Excel (JPL, biaya, penyelenggara).",
  _rekap_classroom_excel_log: "Log proses pembuatan rekap Excel pelatihan.",
  _search_log: "Log pencarian pengguna.",
  _section: "Master section/modul aplikasi.",
  _section_klien: "Pemetaan section ke klien/sumber data.",
  _setting: "Pengaturan umum aplikasi.",
  _survey: "Definisi survei.",
  _survey_member: "Jawaban survei per member.",
  _testimoni_pengajar: "Testimoni untuk pengajar/narasumber.",
  _user: "Akun pengguna back-office/admin (CMS).",
  _user_activity: "Log aktivitas user admin.",
  _user_level: "Master level/role user admin.",
  _user_level_access: "Hak akses per level user admin.",
  _user_reset: "Permintaan reset password user admin.",
  _webinar: "Data webinar.",
  _x_classroom: "Arsip/cadangan kelas (mirror _classroom).",
  _x_classroom2_narsum: "Narasumber kelas versi 2 (arsip) & NPS.",
  _x_classroom_member: "Arsip pendaftaran peserta kelas (mirror _classroom_member).",
  _x_learning_mp_rekap: "Arsip rekap JPL pembelajaran.",
};
